name = "ernisto/ci_cd"
version = "0.1.0"
description = "utilities to write ci_cd luau scripts"
authors = ["ernisto"]
repository = "https://github.com/ernisto/ci-cd"
license = "MIT"

workspace_members = ["pkg/*"]

[engines]
pesde = "^0.7.0-rc.3"
lune = "^0.9.3"

[target]
environment = "lune"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
stylua = { name = "pesde/stylua", version = "^2.1.0" }
luau_lsp = { name = "pesde/luau_lsp", version = "^1.47.0" }
