name = "ernisto/ro_cloud"
version = "0.1.0-alpha"
description = "utilities to access roblox open cloud api"
authors = ["ernisto <joaovitordesouza707@gmail.com>"]
repository = "https://github.com/ernisto/ro-cloud"
license = "MIT"

includes = [
    "lib/**/*.luau",
    "pesde.toml",
    "README.md",
    "LICENSE",
    ".luaurc",
]

[target]
environment = "lune"
lib = "lib/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
