name = "ernisto/semantic_git"
version = "0.1.0-alpha.1"
description = "A library to enforce semantics in your git repository"
authors = ["ernisto <joaovitordesouza707@gmail.com>"]
repository = "https://github.com/ernisto/semantic-git"
license = "MIT"

includes = [
    "config/**/*.luau",
    "utils/**/*.luau",
    "lib/**/*.luau",
    "cli/**/*.luau",
    "pesde.toml",
    "README.md",
    "LICENSE",
    ".luaurc",
]

[target]
environment = "lune"
lib = "lib/init.luau"
bin = "cli/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
git = { workspace = "ernisto/git" }
