name = "ernisto/git"
version = "0.1.0-alpha.8"
description = "library for reading git objects (heavy wip)"
authors = ["ernisto <joaovitordesouza707@gmail.com>"]
repository = "https://github.com/ernisto/git"
license = "MIT"

includes = [
    "src/**/*.luau",
    "pesde.toml",
    "README.md",
    "LICENSE",
    ".luaurc",
]

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
future = { name = "lukadev_0/future", version = "^1.0.1", target = "lune" }
